### ISSUE TITLE
Unable to Import Gradle Project

### ISSUE THREAD

**Issue by navodayasachi** [opentok/accelerator-annotation-android#34]
Cloned git repository, when I tried to import gradle project seeing below error.

Caused by: groovy.lang.GroovyRuntimeException: Cannot set the value of read-only property 'outputFile' for object of type com.android.build.gradle.internal.api.LibraryVariantOutputImpl.

Gradle sync failed: Cannot set the value of read-only property 'outputFile' for object of type com.android.build.gradle.internal.api.LibraryVariantOutputImpl.
				Consult IDE log for more details (Help | Show Log) (650 ms)

**Comment by navodayasachi** [comment]
Tied below resolutions:
https://stackoverflow.com/questions/46829395/gradle-3-0-buildexception-cannot-create-directory/46959050#46959050

https://stackoverflow.com/questions/46949311/cannot-set-the-value-of-read-only-property-outputfile-for-apkvariantoutputimpl/47523816

No Luck!!

**Comment by igorwojda** [comment]
Hello, sorry for long response.
We are currently cleaning up accelerators. I believe that This issue was already adressed in `1.0.4` release. 

I will close this one for now. If you still experience issue please re-open this issue and leave the comment.
